string=input("Enter the list of string\n").split()
print(string)
res=''.join(string)
print(res)
res=res.replace('i','_')
print(res)
res=res.replace('k','i')
print(res)
res=res.replace('_','k')
print(res.split(','))
